name: 发布到 npm

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - run: pnpm install

      - run: pnpm build
      - run: pnpm --filter @fuxishi/svg-icon-element-plus-picker build
      - run: pnpm --filter @fuxishi/svg-icon-naive-picker build
      - run: pnpm --filter @fuxishi/svg-icon-antdv-picker build
      - run: pnpm --filter @fuxishi/svg-icon-tdesign-picker build

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FUXISHI_SVG_ICON }}
      - run: npm publish --access public -w @fuxishi/svg-icon-element-plus-picker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FUXISHI_SVG_ICON }}
      - run: npm publish --access public -w @fuxishi/svg-icon-naive-picker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FUXISHI_SVG_ICON }}
      - run: npm publish --access public -w @fuxishi/svg-icon-antdv-picker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FUXISHI_SVG_ICON }}
      - run: npm publish --access public -w @fuxishi/svg-icon-tdesign-picker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FUXISHI_SVG_ICON }}
